language: python
matrix:
  include:
    - python: 2.7
      env: PYTHON_TAG=py2
    - python: 3.3
      env: PYTHON_TAG=py33
    - python: 3.4
      env: PYTHON_TAG=py34
    - python: 3.5
      env: PYTHON_TAG=py35
    - python: 3.6
      env: PYTHON_TAG=py3

install:
  - pip install -r requirements.txt -r requirements-dev.txt

script:
  - python setup.py clean
  - python setup.py build
  - coverage run --source=pykakasi setup.py test
  - python setup.py bdist_wheel --python-tag=${PYTHON_TAG}

after_success:
  - coveralls

deploy:
  - provider: pypi
    user: miurahr
    password:
      secure: CUY3E7DJMMyC9ARkkC5plAWTAnwmp+wyS+GbRgjOPDL8H4AwzCSCD03D4z/5BHHpGFilF+sAsaNte/9dDjtzEXtvmMCfJwovShnr9GdAm+PU4+TyhEWqVYbeYHiJMiSnLPcsyJMkYZ8JtNMXyp0onPQr6P28OsEq+ohG6Ha9P1Y=
    file_glob: true
    file:
      - dist/*.whl
    skip_cleanup: true
    skip_existing: true
    on:
      repo: miurahr/pykakasi
      tags: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f32fb3bc2d3933f7926f
    on_success: change
    on_failure: always
    on_start: never
