[build-system]
requires = ["setuptools>=45.3.0", "wheel", "setuptools_scm[toml]>=3.5.0", "klepto", "six"]
build-backend = "setuptools.build_meta"

[tools.setuptools_scm]
local_scheme = "no-local-version"

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38, mypy
